test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

minio:
  service: S3
  bucket: <%= ENV['MINIO_BUCKET'] %>
  endpoint: <%= ENV['MINIO_ENDPOINT'] %>
  access_key_id: <%= ENV['MINIO_ROOT_USER'] %>
  secret_access_key: <%= ENV['MINIO_ROOT_PASSWORD'] %>
  region: us-east-1
  force_path_style: true