services:
  vegmod-nginx:
    image: nginx
    env_file: .env
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "9400:9400"
    networks:
      - frontend
      - backend
      - cloudflared

  vegmod-postgres:
    image: postgres:16.3-bookworm
    env_file: .env
    restart: always
    expose:
      - "5432"
    ports:
      - "9401:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - backend

  vegmod-ingress:
    build: ./ingress
    restart: always
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./data/ingress:/app/data

  vegmod-rails:
    image: auguryan/vegmod-rails:latest
    build: ./backend
    command: ./bin/rails s -b 0.0.0.0 -p 9402
    restart: always
    env_file: .env
    volumes:
      - ./logs:/rails/log
      - ./data:/rails/data
      - ./backend/app:/rails/app
      - ./backend/lib:/rails/lib
      - ./backend/config:/rails/config
      - ./backend/db:/rails/db
    ports:
      - "9402:9402"
    networks:
      - backend
      - reddit

  vegmod-rake-cron:
    build: ./rake-cron
    restart: always
    env_file: .env
    volumes:
      - ./logs:/rails/log
      - ./data:/rails/data
    networks:
      - backend
      - reddit

  vegmod-next:
    build: 
      context: ./frontend
      dockerfile: dev.Dockerfile
    restart: always
    env_file: .env
    expose:
      - "3000"
    networks:
      - frontend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src

  vegmod-minio:
    image: bitnami/minio
    user: root
    env_file:
      - .env
    ports:
      - "9403:9403"
      - "9001:9001"
    networks:
      - backend
    volumes:
      - ./data/minio:/bitnami/minio/data

networks:
  cloudflared:
    external: true
  frontend:
  reddit:
  backend:
    internal: true